import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderInfo from "./components/HeaderInfo";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={params.lang}>
      <HeaderInfo />
      <Header />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
